name: Manual Add Booking

on:
  workflow_dispatch:
    inputs:
      booking_date:
        description: "Date to book (DD-MM-YYYY)"
        required: true
        type: string
        default: "DD-MM-YYYY"

jobs:
  add_booking:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run Add Booking Script
        run: node dist/add-booking.js --add ${{ github.event.inputs.booking_date }}

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GIT_COMMIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_COMMIT_USER_EMAIL }}"
          git add bookings.json # Or the correct path
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "chore: Add booking for ${{ github.event.inputs.booking_date }} [skip ci]"
            # The push will be authenticated using the PAT from the checkout step
            git push
          else
            echo "No changes to bookings.json to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
